nav:
    - Introduction: index.md
    - Course-umn-CSci4511w-Class-Notes-on-Search: Course-umn-CSci4511w-Class-Notes-on-Search
    - Course-washington-Search-Cost&Heuristics: Course-washington-Search-Cost&Heuristics
    - Property-of-search-algorithm: Property-of-search-algorithm