nav:
    - Introduction: index.md
    - Structure: Structure.md
    - Transitive-relation: Transitive-relation.md
    - Hierarchy: Hierarchy.md
    - Chain: Chain.md
    - VS-chain-VS-hierarchy: VS-chain-VS-hierarchy.md
    - Describe-structure: Describe-structure.md