nav:
    - Introduction: index.md
    - Relation-based-algorithm-model: Relation-based-algorithm-model.md
    # discrete objects的问题常常会涉及的一种计算方式
    - Iteration: Iteration
    # 归纳与递归
    - Induction-and-Recursion: Induction-and-Recursion 
    - Algorithm: Algorithm
    - Computer-algebra: Computer-algebra
    - Theory-of-computation: Theory-of-computation