nav:
    - Introduction: index.md
    - Hash-function: Hash-function    
    - Hash-table: Hash-table
    - Merkle-tree: Merkle-tree
    - Checksum: Checksum
    - Application: Application
    - Error-detection-and-correction: Error-detection-and-correction