nav:
    - Introduction: index.md
    - Hash-function: Hash-function
    
    - Hash-table: Hash-table
    - Merkle-tree: Merkle-tree
    - Checksum: Checksum
    - Hash-application: Hash-application
    - Error-detection-and-correction: Error-detection-and-correction