nav:
    - Introduction: index.md
    - Majority-problem: Majority-problem
    - First-letter-to-appear-n-times: First-letter-to-appear-n-times
    - LeetCode-1207-独一无二的出现次数-简单: LeetCode-1207-独一无二的出现次数-简单
    
    