nav:
    - Introduction: index.md
    - wikipedia-Dynamic-programming: wikipedia-Dynamic-programming
    - geeksforgeeks-Dynamic-Programming: geeksforgeeks-Dynamic-Programming
    - Expert-Accagain: Expert-Accagain
    - Catalan: Catalan  
    - Subsequence-子序列问题: Subsequence-子序列问题
    - LeetCode: LeetCode
    
