nav:
    - Introduction: index.md
    - wikipedia-Dynamic-programming: wikipedia-Dynamic-programming
    - geeksforgeeks-Dynamic-Programming: geeksforgeeks-Dynamic-Programming
    - CSDN-DP算法分类总结: CSDN-DP算法分类总结
    - 最大子段和: 最大子段和
    - Catalan: Catalan  
    
