nav:
    - Introduction: index.md
    - wikipedia-Dynamic-programming: wikipedia-Dynamic-programming
    - geeksforgeeks-Dynamic-Programming: geeksforgeeks-Dynamic-Programming
    - Expert-Accagain: Expert-Accagain
    - Catalan: Catalan  
    - DP解子序列问题: DP解子序列问题
    - DP解子数组问题: DP解子数组问题
    - DP解数位问题: DP解数位问题
    - DP解区间问题: DP解区间问题
    - 树形DP: 树形DP
    - DP解最短路径问题: DP解最短路径问题
    - LeetCode: LeetCode
    
