nav:
    - Introduction: index.md
    
    - 0-必读系列: 0-必读系列
    
    - 1-动态规划系列: 1-动态规划系列
    
    - 2.2-手把手刷链表题目: 2.2-手把手刷链表题目

    - 2.3-手把手刷二叉树: 2.3-手把手刷二叉树
    
    - 2.4-手把手设计数据结构: 2.4-手把手设计数据结构
    
    - 2.5-手把手刷数组题目: 2.5-手把手刷数组题目
    
    - 3.1-回溯算法(DFS算法)系列: 3.1-回溯算法(DFS算法)系列
    
    - 3.2-BFS算法系列: 3.2-BFS算法系列
    
    - 3.3-其他算法篇: 3.3-其他算法篇
    
    - 3.4-数学运算技巧: 3.4-数学运算技巧
    
    - 4-高频面试系列: 4-高频面试系列
    
    - 手撕力扣高频面试题: 手撕力扣高频面试题
    
    - 去重: 去重
    
    - 中位数-中点: 中位数-中点
    
    - Palindrome-回文: Palindrome-回文
    
    - 排序: 排序
    