nav:
    - Introduction: index.md
    - 数据结构和算法学习指南: 数据结构和算法学习指南
    - 双指针-滑动窗口-尺取法: 双指针-滑动窗口-尺取法    
    - 动态规划: 动态规划
    - 回溯法: 回溯法
    - 去重: 去重
    - 二叉树的序列化-就那几个框架: 二叉树的序列化-就那几个框架
    - 高频面试系列: 高频面试系列
    
    