nav:
    - Linked-list-nth-node: Linked-list-nth-node
    - Linked-list去重系列: Linked-list去重系列
    - Linked-list-delete-node: Linked-list-delete-node
    - Common-node-in-linked-list: Common-node-in-linked-list    
    - Reverse-linked-list: Reverse-linked-list
    - Sort-linked-list: Sort-linked-list
    - Reverse-linked-list: Reverse-linked-list
