nav:
    - Introduction: index.md
    - All-nearest-smaller&Next-greater-number: All-nearest-smaller&Next-greater-number
    - Max-min-lexicographical-order-subsequence: Max-min-lexicographical-order-subsequence
    - LeetCode-Monotonic-stack: LeetCode-Monotonic-stack
    