nav:
    - Introduction: index.md
    - All-nearest-smaller-values: All-nearest-smaller-values
    - Next-Greater-Number: Next-Greater-Number
    - Max-min-lexicographical-order-subsequence: Max-min-lexicographical-order-subsequence
    - LeetCode-Monotonic-stack: LeetCode-Monotonic-stack
    - Monotonic-stack-VS-dynamic-programming: Monotonic-stack-VS-dynamic-programming
    