nav:
    - Introduction: index.md
    - All-nearest-smaller-values: All-nearest-smaller-values
    - Stack-sortable-permutation: Stack-sortable-permutation
    - Max-min-lexicographical-order-subsequence: Max-min-lexicographical-order-subsequence
    