nav:
    - Introduction: index.md
    - Application: Application    
    - paper-An-efficient-representation-for-solving-Catalan-number-related-problems: paper-An-efficient-representation-for-solving-Catalan-number-related-problems
    
