nav:
    - Introduction: index.md
    - Tree-structure: Tree-structure
    - Tree-representation: Tree-representation    
    - Tree-data-structure: Tree-data-structure
    - Search-tree: Search-tree
    - Disjoint-set: Disjoint-set
    - Implementation: Impl
    - Tree-algorithm: Tree-algorithm
    - Application: Application    
