nav:
    - Introduction: index.md
    - Tree-structure: Tree-structure
    - Represent-tree: Represent-tree    
    - Tree-data-structure: Tree-data-structure
    - Parenthese-and-tree: Parenthese-and-tree
    - Tree-operation: Operation
    - Search-tree: Search-tree
    - Disjoint-set: Disjoint-set
    - Implementation: Impl
    - Application: Application    
    - LeetCode: LeetCode