nav:
    - Introduction: index.md
    - Tree-structure: Tree-structure
    - Tree(data-structure): Tree(data-structure)
    - Represent-describe-tree: Represent-describe-tree
    - Parenthese-and-tree: Parenthese-and-tree
    - Tree-operation: Tree-operation
    - TODO-Rank-of-node: TODO-Rank-of-node
    - Application-of-tree: Application-of-tree.md
    - Implicit-tree: Implicit-tree
    
    - Trie: Trie
    - Disjoint-set: Disjoint-set
    - VS-of-tree: VS-of-tree.md
    - Implementation: Implementation
    - TODO: TODO.md
    - LeetCode: LeetCode