nav:
    - Introduction: index.md
    - Tree-structure: Tree-structure
    - Represent-tree: Represent-tree    
    - Tree-data-structure: Tree-data-structure
    - Tree-algorithm: Tree-algorithm
    - Search-tree: Search-tree
    - Disjoint-set: Disjoint-set
    - Implementation: Impl
    - Application: Application    
