nav:
    - Introduction: index.md
    - wikipedia-Algorithmic-paradigm: wikipedia-Algorithmic-paradigm   
    - Brute-force: Brute-force
    - Divide-and-Conquer: Divide-and-Conquer
    - DP&Greedy: DP&Greedy
    - Heuristic: Heuristic
    - Statistical-algorithms: Statistical-algorithms