nav:
    - Introduction: index.md
    - Array: Array
    - Linked-list: Linked-list
    - Stack: Stack    
    - Graph: Graph
    - Tree: Tree    
    - Set: Set
    - Probabilistic-data-structures: Probabilistic-data-structures
    - Hash: Hash
    - Summary: Summary
    - TODO: TODO.md