nav:
    - Introduction: index.md
    - Guide: Guide    
    - ADT&Impl: ADT&Impl
    - Array: Array
    - Linked-list: Linked-list
    - Stack: Stack    
    - Graph: Graph
    - Tree: Tree
    - Hash: Hash
    - Probabilistic-data-structures: Probabilistic-data-structures
    - Judy-array: Judy-array
    - String: String
    - Associative-array&set: Associative-array&set
    - Priority-queue: Priority-queue
        