nav:
    - Introduction: index.md
    - Guide: Guide    
    - Array: Array
    - Linked-list: Linked-list
    - Stack: Stack    
    - Graph: Graph
    - Tree: Tree
    - Heap: Heap
    - Hash: Hash
    - Probabilistic-data-structures: Probabilistic-data-structures
    - Judy-array: Judy-array
    - String: String
    - TODO: TODO.md