nav:
    - Introduction: index.md
    - External-sorting: External-sorting
    - 从大量URL中找出相同URL: 从大量URL中找出相同URL
    - 不重复的数字: 不重复的数字
    - 从5亿个数中找出中位数: 从5亿个数中找出中位数
    - Top-K: Top-K
    - 按照query频率排序: 按照query频率排序
    
    