nav:
    - HJ1-字符串最后一个单词的长度: HJ1-字符串最后一个单词的长度
    - HJ2-计算某字符出现次数: HJ2-计算某字符出现次数
    - HJ3-明明的随机数: HJ3-明明的随机数
    - HJ4-字符串分隔: HJ4-字符串分隔
    - HJ5 进制转换: HJ5 进制转换
    - HJ6-质数因子: HJ6-质数因子
    
                
