nav:
    - HJ1-字符串最后一个单词的长度: HJ1-字符串最后一个单词的长度
    - HJ2-计算某字符出现次数: HJ2-计算某字符出现次数
    - HJ3-明明的随机数: HJ3-明明的随机数
    - HJ4-字符串分隔: HJ4-字符串分隔
    - HJ5 进制转换: HJ5 进制转换
    - HJ6-质数因子: HJ6-质数因子
    - HJ7-取近似值: HJ7-取近似值
    - HJ8-合并表记录: HJ8-合并表记录
    - HJ9-提取不重复的整数: HJ9-提取不重复的整数
    - HJ10-字符个数统计: HJ10-字符个数统计
    - HJ11-数字颠倒: HJ11-数字颠倒
    - HJ12-字符串反转: HJ12-字符串反转
    - HJ13-句子逆序: HJ13-句子逆序
    - HJ14-字符串排序: HJ14-字符串排序
    - HJ15-求int型正整数在内存中存储时1的个数: HJ15-求int型正整数在内存中存储时1的个数    
    - HJ16-购物单: HJ16-购物单
    - HJ20-密码验证合格程序: HJ20-密码验证合格程序
    - HJ50-四则运算: HJ50-四则运算
    - HJ51-输出单向链表中倒数第k个结点: HJ51-输出单向链表中倒数第k个结点
    - HJ52-计算字符串的编辑距离: HJ52-计算字符串的编辑距离