nav:
    - HJ1-字符串最后一个单词的长度: HJ1-字符串最后一个单词的长度
    - HJ2-计算某字符出现次数: HJ2-计算某字符出现次数
    - HJ3-明明的随机数: HJ3-明明的随机数
    - HJ4-字符串分隔: HJ4-字符串分隔
    - HJ5 进制转换: HJ5 进制转换
    - HJ6-质数因子: HJ6-质数因子
    - HJ7-取近似值: HJ7-取近似值
    - HJ8-合并表记录: HJ8-合并表记录
    - HJ9-提取不重复的整数: HJ9-提取不重复的整数
    - HJ10-字符个数统计: HJ10-字符个数统计
    - HJ11-数字颠倒: HJ11-数字颠倒
    - HJ12-字符串反转: HJ12-字符串反转
        
