nav:
    - Introduction: index.md
    - Unrolled-linked-list: Unrolled-linked-list
    - Double-linked-list: Double-linked-list    
    
    - Sentinel-node: Sentinel-node
    - TODO-Dummy-node: TODO-Dummy-node
    - Circle-detection: Circle-detection
    - LeetCode: LeetCode