nav:
    - Introduction: index.md
    - Double-linked-list: Double-linked-list    
    - VS-double-linked-list-VS-binary-tree: VS-double-linked-list-VS-binary-tree.md
    - VS-Unrolled-linked list-VS-B-tree: VS-Unrolled-linked list-VS-B-tree.md
    - Sentinel-node: Sentinel-node
    - Circle-detection: Circle-detection
    - LeetCode-linked-list: LeetCode-linked-list