nav:
    - Introduction: index.md
    
    - Bubble-Sort: Bubble-Sort
    
    - Insertion-sort: Insertion-sort
    
    - Quick-sort: Quick-sort
    
    - Merge-sort: Merge-sort
    
    - Heapsort: Heapsort
    
    - Shellsort: Shellsort
    
    - Lexicographical-order: Lexicographical-order   
    