nav:
    - Introduction: index.md
    
    - Bubble-Sort: Bubble-Sort
    
    - Insertion-sort: Insertion-sort
    
    - Quick-sort-select: Quick-sort-select
    
    - Merge-sort: Merge-sort
    
    - Heap-sort-select: Heap-sort-select
    
    - Shellsort: Shellsort
    
    - Lexicographical-order: Lexicographical-order   
    