nav:
    - Introduction: index.md
    - Subset: Subset # 子集
    - Sudoku-solving: Sudoku-solving
    - N-queen: N-queen
    - Symbol-triangle: Symbol-triangle    
    - M-coloring-of-graph: M-coloring-of-graph
    