nav:
    - Introduction: index.md    
    - Brute-force: 00-Brute-force
    - Divide-and-Conquer: 01-Divide-and-Conquer
    - Dynamic-Programming&Greedy-Algorithm: 02-Dynamic-Programming&Greedy-Algorithm
    - Backtracking: Backtracking
    - Branch-and-Bound-Algorithm: 06-Branch-and-Bound-Algorithm
    - Heuristic: Heuristic
    - Brute-force-VS-backtrack: Brute-force-VS-backtrack.md