nav:
    - Summary-of-search-method: Summary-of-search-method
    - DFS-and-BFS: DFS-and-BFS.md
    - A-star-search-algorithm: A-star-search-algorithm.md
    - Beam-search: Beam-search.md
    - Iterative-deepening-depth-first-search: Iterative-deepening-depth-first-search.md
    - Best-first-search: Best-first-search.md
    