nav:
    - Introduction: index.md
    - wikipedia-Search-algorithm: wikipedia-Search-algorithm
    - Double-pointer-search: Double-pointer-search # 可以看做是search       
    - State-space-search: State-space-search # 可以看做是search       

    