nav:
    - Introduction: index.md
    - wikipedia-Binary-search-algorithm: wikipedia-Binary-search-algorithm
    - Complexity-analysis: Complexity-analysis
    - src: src
    - LeetCode-35-搜索插入位置-简单: LeetCode-35-搜索插入位置-简单
    - LeetCode-34-在排序数组中查找元素的第一个和最后一个位置-中等: LeetCode-34-在排序数组中查找元素的第一个和最后一个位置-中等
    - LeetCode-540-有序数组中的单一元素-中等: LeetCode-540-有序数组中的单一元素-中等
    