nav:
    - Introduction: index.md
    - Perfect-hash-function: Perfect-hash-function
    - Rolling-hash: Rolling-hash
    - Geometric-hashing: Geometric-hashing
    - SipHash: SipHash
    - Cryptographic-hash-functions: Cryptographic-hash-functions
    - Linear-hash: Linear-hash
    - Implementation: Implementation    
    