nav:
    - Introduction: index.md
    - wikipedia-Matrix-chain-multiplication: wikipedia-Matrix-chain-multiplication
    - geeksforgeeks-Matrix-Chain-Multiplication: geeksforgeeks-Matrix-Chain-Multiplication
    