nav:
    - Introduction: index.md
    - Graph-cycle-resolve: Graph-cycle-resolve
    - Graph-cycle-detection: Graph-cycle-detection
    - Linked-list-cycle-detection: Linked-list-cycle-detection
    - Max-Cycle: Max-Cycle
    