nav:
    - Introduction: index.md
    - wikipedia-Master-theorem(analysis-of-algorithms): wikipedia-Master-theorem(analysis-of-algorithms)
    - YSC2229-4.4-Complexity-of-Divide-and-Conquer-Algorithms: YSC2229-4.4-Complexity-of-Divide-and-Conquer-Algorithms