nav:
    - Introduction: index.md
    - Book-Introduction-to-Algorithms: Book-Introduction-to-Algorithms
    - 算法思维: 算法思维    
    - State-space-search: State-space-search # 可以看做是search       
    - Paradigm: Paradigm
    - Analysis: Analysis
    - Binary-search: Binary-search # 可以看做是search       
    - Sorting: Sorting  
    - Classical-algorithm: Classical
    - Application: Application
   
    - 穷举-VS-DP-VS-greedy: 穷举-VS-DP-VS-greedy

    