nav:
    - Introduction: index.md
    - Paradigm: Paradigm

    - Search: Search
    - State-space-search: State-space-search       
    - Sorting: Sorting    
    - Classical-algorithm: Classical
 
    - Application: Application

