nav:
    - Introduction: index.md
    - Books: Books
    - 算法思维: 算法思维    
    - Search-algorithms: Search-algorithms # 可以看做是search       
    - Sorting-algorithms: Sorting-algorithms
    - Paradigms: Paradigms
    - Analysis: Analysis
    - Application: Application
    - 穷举-VS-DP-VS-greedy: 穷举-VS-DP-VS-greedy

    