nav:
    - Introduction: index.md
    - Paradigm: Paradigm
    - Randomized-algorithm: Randomized-algorithm
    - Analysis: Analysis
    - Search: Search
    - Binary-search: Binary-search # 可以看做是search       
    - State-space-search: State-space-search # 可以看做是search       
    - Sorting: Sorting    
    - Classical-algorithm: Classical
    - Application: Application

