nav:
    - Introduction: index.md
    - wikipedia-String(computer-science): wikipedia-String(computer-science)
    - Pattern-match: Pattern-match
    - String-search: String-search
    - LeetCode: LeetCode