nav:
    - Introduction: index.md
    - Bracket(tournament): Bracket(tournament)
    - Matched-balanced-parentheses: Matched-balanced-parentheses
    - Depth-of-nested-parenthesis: Depth-of-nested-parenthesis
    - Bracket(tournament): Bracket(tournament)
    - Construct-binary-tree-from-parenthesis: Construct-binary-tree-from-parenthesis
    - LeetCode-22-Generate-Parentheses-middle: LeetCode-22-Generate-Parentheses-middle
    