nav:
    - Introduction: index.md
    - labuladong-单调栈Monotonic-Stack的使用: labuladong-单调栈Monotonic-Stack的使用
    - labuladong-单调栈解题模板秒杀三道算法题: labuladong-单调栈解题模板秒杀三道算法题
    - All-nearest-smaller-values: All-nearest-smaller-values
    - Stack-sortable-permutation: Stack-sortable-permutation
    - Monotonic-stack解Max-min-subsequence-子序列: Monotonic-stack解Max-min-subsequence-子序列