nav:
    - Introduction: index.md
    - Traverse-linked-list: Traverse-linked-list
    - DFS-linked-list: DFS-linked-list
    - Previous-current-next-pointer-三指针: Previous-current-next-pointer-三指针
    - Fast-slow-double-pointer-快慢双指针: Fast-slow-double-pointer-快慢双指针
    - 去重: 去重
    - 公共节点: 公共节点    
    - Reverse-linked-list: Reverse-linked-list
    - Sort-linked-list: Sort-linked-list
    - Circle-detection: Circle-detection
    