nav:
    - index: index.md
    - Great-Theoretical-Ideas-in-Computer-Science: Great-Theoretical-Ideas-in-Computer-Science
    - Theory-of-computation: Theory-of-computation.md
    - Model-of-computation: Model-of-computation
    - Computability-theory: Computability-theory
    - Computational-complexity-theory: Computational-complexity-theory
    - Automata-theory&formal-language: Automata-theory&formal-language

