nav:
    - Introduction: index.md
    - wikipedia-Stack(abstract-data-type): wikipedia-Stack(abstract-data-type)
    - geeksforgeeks-Stack-Data-Structure: geeksforgeeks-Stack-Data-Structure.md
    # 单调栈
    - Monotonic-stack: Monotonic-stack 
    # 对栈进行排序
    - Sort-stack: Sort-stack
    # 栈和队列
    - Stack-and-queue: Stack-and-queue
    
    - 反转-reverse-stack: 反转-reverse-stack
    # 使用栈来进行反转
    - 反转-reverse-by-stack: 反转-reverse-by-stack
    
    - Application-of-stack: Application-of-stack.md    
    - All-nearest-smaller-values: All-nearest-smaller-values