nav:
    - Introduction: index.md
    - LeetCode-303-Range-Sum-Query-Easy: LeetCode-303-Range-Sum-Query-Easy
    - LeetCode-307-Range-Sum-Query-Mutable-Medium: LeetCode-307-Range-Sum-Query-Mutable-Medium
    
    