nav:
    - Dynamic-programming: Dynamic-programming.md
    - Overlapping-subproblems: Overlapping-subproblems.md
    - VS-最长公共子序列-VS-矩阵连乘问题-VS-最大子段和: VS-最长公共子序列-VS-矩阵连乘问题-VS-最大子段和.md
    - Catalan: Catalan.md
    - Reading-list: Reading-list.md