nav:
    - Introduction: index.md
    - 经典动态规划-0-1 背包问题: 经典动态规划-0-1 背包问题
    - LeetCode-一篇文章吃透背包问题: LeetCode-一篇文章吃透背包问题
    - 算法设计与分析-3.10-0-1背包问题: 算法设计与分析-3.10-0-1背包问题
    - LeetCode-322-零钱兑换: LeetCode-322-零钱兑换
    - TODO-518-零钱兑换-II: TODO-518-零钱兑换-II
    - TODO-LeetCode-279-完全平方数: TODO-LeetCode-279-完全平方数
    - TODO-LeetCode-416-分割等和子集: TODO-LeetCode-416-分割等和子集
    - TODO-LeetCode-494-目标和: TODO-LeetCode-494-目标和
    - TODO-LeetCode-1046-最后一块石头的重量: TODO-LeetCode-1046-最后一块石头的重量
    - TODO-LeetCode-1049-最后一块石头的重量-II: TODO-LeetCode-1049-最后一块石头的重量-II
    - TODO-LeetCode-1155-掷骰子的N种方法: TODO-LeetCode-1155-掷骰子的N种方法