nav:
    - Introduction: index.md
    - 数学-数字: 数学-数字
    - Subsequence-Subarray-Substring: Subsequence-Subarray-Substring    
    - 区间: 区间
    - int&string: int&string # int&string 和 DFA 是密切相关的，要将两者放到一起
    - Parse: Parse
    - Partition-划分: Partition-划分
    - 设计数据结构: 设计数据结构
    - 技巧总结: 技巧总结
    - Tournament-比赛: Tournament-比赛
    - 模拟: 模拟
    - Huawei-机试: Huawei-机试
    - 无限流-stream: 无限流-stream
    