nav:
    - Introduction: index.md
    - LeetCode-16.19-水域大小: LeetCode-16.19-水域大小


    - 打家劫舍-House-robber: 打家劫舍-House-robber

    - stack: stack
    - Subsequence(子序列)-Subarray(子数组)-Substring(子串): Subsequence(子序列)-Subarray(子数组)-Substring(子串)
    - Tournament-比赛: Tournament-比赛