nav:
    - Introduction: index.md
    - Math-number: Math-number
    # merge、reverse、partition、split等是非常常见的一些题目，并且它们的出题方式有些类似
    - Reverse: Reverse
    - Merge: Merge
    - Partition: Partition
    
    - Optimization: Optimization
    - Subsequence-Subarray-Substring: Subsequence-Subarray-Substring    
    - 区间: 区间
    - Parse: Parse

    - 设计数据结构: 设计数据结构
    - 技巧总结: 技巧总结
    - Tournament: Tournament
    - 模拟: 模拟
    - Huawei-机试: Huawei-机试

    - Automaton: Automaton
    - 简化代码: 简化代码
    - LeetCode-Range-Sum-Query: LeetCode-Range-Sum-Query