nav:
    - Introduction: index.md
    - 数学-数字: 数学-数字
    - Subsequence-Subarray-Substring: Subsequence-Subarray-Substring    
    - int&string: int&string
    - Partition-划分: Partition-划分
    - 数据结构设计: 数据结构设计
    - 技巧总结: 技巧总结
    - Tournament-比赛: Tournament-比赛
    