nav:
    - Mathematical-optimization: Mathematical-optimization.md
    - Loss-function-or-Objective-function: Loss-function-or-Objective-function.md
    - Iterative-optimization-algorithm: iterative-optimization-algorithm.md
    - Iterative-method: Iterative-method.md
    - Hill-climbing: Hill-climbing.md