nav:
    - Introduction: index.md
    # 这是核心所在
    - Relation-structure-computation: Relation-structure-computation
    # 组合学
    - Combinatorics: Combinatorics
    # discrete objects的问题常常会涉及的一种计算方式
    - Iteration: Iteration
    # 归纳与递归
    - Induction-and-Recursion: Induction-and-Recursion
    # 关系
    - Relation: Relation    