nav:
    - Introduction: index.md
    - Chapter-2-Basic-Structures: Chapter-2-Basic-Structures
    - Chapter-5-Induction-and-Recursion: Chapter-5-Induction-and-Recursion
    - Chapter-6-Counting: Chapter-6-Counting
    - Chpater-9-Relations: Chpater-9-Relations