nav:
    - Introduction: index.md
    - LeetCode-141-环形链表: LeetCode-141-环形链表
    - LeetCode-147-对链表进行插入排序: LeetCode-147-对链表进行插入排序
    - 去重: 去重
    - LeetCode-面试题-02.02-返回倒数第k个节点- LeetCode-面试题-02.02-返回倒数第k个节点
    - 公共节点: 公共节点