nav:
    - Introduction: index.md
    - Capitalize-upper-lower: Capitalize-upper-lower
    - Stock-code: Stock-code
    - Percentage: Percentage
    - CamelCase&under_score_case&snake-case: CamelCase&under_score_case&snake-case
    - Lookaround: Lookaround
    