nav:
    - Introduction: index.md
    - 如何判定括号合法性: 如何判定括号合法性
    - 回溯算法最佳实践-括号生成: 回溯算法最佳实践-括号生成
    - 手把手解决三道括号相关的算法题: 手把手解决三道括号相关的算法题
    - LeetCode-20-有效的括号: LeetCode-20-有效的括号
    - LeetCode-921-使括号有效的最少添加: LeetCode-921-使括号有效的最少添加
    