nav:
    - Introduction: index.md
    - State-solution-space: State-solution-space
    - Divide-and-Conquer: Divide-and-Conquer
    - Overlapping-subproblem: Overlapping-subproblem
    - Space-time-tradeoff: Space-time-tradeoff
    - Recurrence-relation递归状态转移方程: Recurrence-relation递归状态转移方程
    - wikipedia-Analysis-of-algorithms: wikipedia-Analysis-of-algorithms
    