nav:
    - Introduction: index.md
    - Combinational-analysis: Combinational-analysis
    - Constraint-satisfaction-problem: Constraint-satisfaction-problem.md
    - Strategy: Strategy
    - Application: App
    