nav:
    - Introduction: index.md
    - List-of-data-structure: List-of-data-structure

    - Graph-and-tree-and-list: Graph-and-tree-and-list
    - Implementation-of-ADT: Implementation-of-ADT.md
    - Dict-map: Dict-map
