nav:
    - Introduction: index.md
    - List-of-data-structure: List-of-data-structure

    - Graph-and-tree-and-list: Graph-and-tree-and-list
    - Implementation-of-ADT: Implementation-of-ADT.md
    - Associative-array-implementation: Associative-array-implementation
    - Search-tree-and-skip-list: Search-tree-and-skip-list.md