nav:
    - 动态规划设计之最长递增子序列: 动态规划设计之最长递增子序列
    - 从最长递增子序列学会如何推状态转移方程: 从最长递增子序列学会如何推状态转移方程
    - LeetCode-300-最长递增子序列: LeetCode-300-最长递增子序列
    - LeetCode-491-递增子序列-中等: LeetCode-491-递增子序列-中等
    - LeetCode-673-最长递增子序列的个数: LeetCode-673-最长递增子序列的个数
    - LeetCode-674-最长连续递增序列: LeetCode-674-最长连续递增序列
    