nav:
    - Introduction: index.md
    - Backtrack-enum-all-permutations-of-string: Backtrack-enum-all-permutations-of-string
    - Enum-distinct-permutation-of-with-duplicate: Enum-distinct-permutation-of-with-duplicate

    