nav:
    - Introduction: index.md
    - Graph-traversal: Graph-traversal
    - Shortest-longest-path: Shortest-longest-path
    - Topological-sorting: Topological-sorting
    - Spanning-tree: Spanning-tree    
    - Search-algorithm: Search-algorithm # graph和tree中都会存在的一种问题
    - Circular: Circular
    - Dominator: Dominator
    - Closure: Closure
    - Graph-DP: Graph-DP    
    - Flood-Fill-泛洪算法: Flood-Fill-泛洪算法    
    - LeetCode: LeetCode    
