nav:
    - Introduction: index.md
    - Graph-algorithm-paradigm: Graph-algorithm-paradigm
    - Traverse-graph: Traverse-graph
    - Spanning-tree: Spanning-tree    
    - Graph-cycle-detection: Graph-cycle-detection
    - Dominator: Dominator
    - Connected-component: Connected-component
    - Search-graph: Search-graph
    - LeetCode: LeetCode    
    - Tree&graph: Tree&graph
    
