nav:
    - Introduction: index.md
    - Graph-algorithm-paradigm: Graph-algorithm-paradigm
    - Traverse-graph: Traverse-graph
    - Shortest-longest-path: Shortest-longest-path
    - Topological-sorting: Topological-sorting
    - Spanning-tree: Spanning-tree    
    - Cycle: Cycle
    - Dominator: Dominator
    - Connected-component: Connected-component
    - LeetCode: LeetCode    
