nav:
    - Introduction: index.md    
    - Backtracking: Backtracking
    - Branch-and-Bound: Branch-and-Bound
    - Branch-and-bound-Algorithm: Branch-and-bound
    - Compared-with-brute-force: Compared-with-brute-force.md