nav:
    - Introduction: index.md
    - Tree-structure:  Tree-structure.md
    - Examples-of-tree-structures: Examples-of-tree-structures.md
    - Represent-tree: Represent-tree.md
    - Tree(set-theory): Tree(set-theory).md
    - Tree(data-structure): Tree(data-structure).md
    - Application-of-tree-data-structure: Application-of-tree-data-structure.md
    - Implicit-tree: Implicit-tree.md
    - Tree-model: Tree-model.md
    - Tree-operation: Tree-operation
    - Trie: Trie
    - TODO: TODO.md