nav:
    - Introduction: index.md
    - LeetCode-一篇文章吃透背包问题: LeetCode-一篇文章吃透背包问题
    - LeetCode-322-零钱兑换: LeetCode-322-零钱兑换
    - LeetCode-518-零钱兑换-II: LeetCode-518-零钱兑换-II
    - LeetCode-279-完全平方数: LeetCode-279-完全平方数
    - LeetCode-416-分割等和子集: LeetCode-416-分割等和子集
    - LeetCode-494-目标和: LeetCode-494-目标和
    - TODO-LeetCode-1046-最后一块石头的重量: TODO-LeetCode-1046-最后一块石头的重量
    - TODO-LeetCode-1049-最后一块石头的重量-II: TODO-LeetCode-1049-最后一块石头的重量-II
    - LeetCode-1155-掷骰子的N种方法: LeetCode-1155-掷骰子的N种方法
    