nav:
    - Previous-current-next-pointer: Previous-current-next-pointer    
    - Fast-slow-double-pointer-快慢双指针: Fast-slow-double-pointer-快慢双指针
    - 排序-sort: 排序-sort
    - 去重: 去重
    - Merge-合并: Merge-合并
    - 公共节点: 公共节点    
    - Reverse-反转: Reverse-反转

