nav:
    - Introduction: index.md
    - labuladong-最长回文子串: labuladong-最长回文子串
    - labuladong-如何高效判断回文单链表: labuladong-如何高效判断回文单链表
    - labuladong-构造回文的最小插入次数: labuladong-构造回文的最小插入次数
    - Palindrome-string: Palindrome-string
    - Palindrome-linked-list: Palindrome-linked-list
    - LeetCode-5-最长回文子串: LeetCode-5-最长回文子串
    - LeetCode-214-最短回文串: LeetCode-214-最短回文串    
    - LeetCode-234-回文链表-简单: LeetCode-234-回文链表-简单        
    - LeetCode-409-最长回文串: LeetCode-409-最长回文串
    - LeetCode-647-回文子串: LeetCode-647-回文子串
    
