nav:
    - Introduction: index.md
    - Finite-state-automaton-based-string-search-algorithm: Finite-state-automaton-based-string-search-algorithm
    - Rabin-Karp-algorithm: Rabin-Karp-algorithm
    - LCS-longest-common-substring: LCS-longest-common-substring
    