nav:
    - Introduction: index.md
    - Knuth-Morris-Pratt-algorithm: Knuth-Morris-Pratt-algorithm
    - Rabin-Karp-algorithm: Rabin-Karp-algorithm
    - LCS-longest-common-substring: LCS-longest-common-substring
    - LeetCode-28-实现strStr: LeetCode-28-实现strStr
    - LeetCode-796-旋转字符串: LeetCode-796-旋转字符串
    - LeetCode-1392-最长快乐前缀-困难: LeetCode-1392-最长快乐前缀-困难
    