nav:
    - labuladong-论那些小而美的算法技巧-差分数组前缀和: labuladong-论那些小而美的算法技巧-差分数组前缀和
    - labuladong-前缀和技巧-解决子数组问题: labuladong-前缀和技巧-解决子数组问题
    - TODO-Prefix-sum-array-and-difference-array: TODO-Prefix-sum-array-and-difference-array
    - Difference-array: Difference-array
    - wikipedia-Prefix-sum: wikipedia-Prefix-sum
    