nav:
    - Introduction: index.md
   
    - Relation: Relation
    # 结构，结构就是典型的具备离散特性的
    - Structure: Structure
    # 关系
    - Computation: Computation
    - Model: Model
    # 使用 Relation-structure-computation 章节中的思想来进行分析    
    - Function-recursion-tree-stack: Function-recursion-tree-stack