nav:
    - Introduction: index.md
    - Structuralization-and-formalization: Structuralization-and-formalization
    # 关系
    - Relation: Relation
    # 结构，结构就是典型的具备离散特性的
    - Structure: Structure
    - Computation: Computation
    - Model: Model
    - Symbol: Symbol