nav:
    - Introduction: index.md
    - Dijkstra's-algorithm: Dijkstra's-algorithm
    - Bellman–Ford-algorithm: Bellman–Ford-algorithm
    - SPFA-Shortest-Path-Faster-Algorithm: SPFA-Shortest-Path-Faster-Algorithm
    - Floyd–Warshall-algorithm: Floyd–Warshall-algorithm
    - LeetCode-787-K站中转内最便宜的航班: LeetCode-787-K站中转内最便宜的航班
    - LeetCode-743-网络延迟时间-中等: LeetCode-743-网络延迟时间-中等
    - LeetCode-847-访问所有节点的最短路径-困难: LeetCode-847-访问所有节点的最短路径-困难 
    - LeetCode-1631-最小体力消耗路径: LeetCode-1631-最小体力消耗路径
    - LeetCode-1928-规定时间内到达终点的最小花费: LeetCode-1928-规定时间内到达终点的最小花费
