nav:
    - Introduction: index.md
    - BFS-shortest-path: BFS-shortest-path    
    - Dijkstra's-algorithm: Dijkstra's-algorithm
    - Dijkstra's-algorithm-VS-BFS: Dijkstra's-algorithm-VS-BFS
    - Bellman–Ford-algorithm: Bellman–Ford-algorithm
    - Edge-relaxation: Edge-relaxation
    - SPFA-Shortest-Path-Faster-Algorithm: SPFA-Shortest-Path-Faster-Algorithm
    - Floyd–Warshall-algorithm: Floyd–Warshall-algorithm
    - LeetCode: LeetCode
