nav:
    - Introduction: index.md
    - 数学-数字: 数学-数字
    - Subsequence-Subarray-Substring: Subsequence-Subarray-Substring    
    - LeetCode-16.19-水域大小: LeetCode-16.19-水域大小

    - Tournament-比赛: Tournament-比赛