nav:
    - Introduction: index.md
    - wikipedia-Dynamic-programming: wikipedia-Dynamic-programming
    - geeksforgeeks-Dynamic-Programming: geeksforgeeks-Dynamic-Programming
    - Expert-Accagain: Expert-Accagain
    - Catalan-DP: Catalan-DP
    - Fibonacci-DP: Fibonacci-DP
    - 背包DP: 背包DP
    - Interval-DP: Interval-DP
    - Tree-DP: Tree-DP
    - LeetCode: LeetCode
    
