nav:
    - Computational-problems-in-graph-theory: Computational-problems-in-graph-theory.md
    - Circular: Circular
    - Dominator: Dominator
    - Sorting: Sorting
    - Spanning-tree: Spanning-tree