nav:
    - Introduction: index.md
    - LRU-LFU: LRU-LFU
    - 设计最大频率栈: 设计最大频率栈
    - 设计朋友圈时间线功能: 设计朋友圈时间线功能    
    - Monotonic-stack单调栈: Monotonic-stack单调栈
    - 单调队列解决滑动窗口问题: 单调队列解决滑动窗口问题
    - 二叉堆实现优先级队列: 二叉堆实现优先级队列

    
    