nav:    
    - yale-Course-YSC2229-Introductory-Data-Structures-and-Algorithms: yale-Course-YSC2229-Introductory-Data-Structures-and-Algorithms
    - cornell-cs3110: cornell-cs3110
    - washington-CSE373-Data-Structures-and-Algorithms: washington-CSE373-Data-Structures-and-Algorithms
    

    