nav:
    - Introduction: index.md
    - DFS-stack-machine: DFS-stack-machine
    - DFS-backtrack: DFS-backtrack
    - BFS-queue-machine: BFS-queue-machine
    - BFS-branch-and-bound: BFS-branch-and-bound    

    