nav:
    - Introduction: index.md
    - wikipedia-Dynamic-programming: wikipedia-Dynamic-programming
    - Overlapping-subproblems: Overlapping-subproblems.md
    - LCS-最长公共子序列: LCS-最长公共子序列
    - VS-最长公共子序列-VS-矩阵连乘问题-VS-最大子段和: VS-最长公共子序列-VS-矩阵连乘问题-VS-最大子段和.md

    - Reading-list: Reading-list.md