nav:
    - Introduction: index.md
    - Relation: Relation.md
    - Entity–relationship-model: Entity–relationship-model
    - Order-theory: Order-theory
    - Structure-and-relation: Structure-and-relation.md