nav:
    - Backtracking: Backtracking.md
    - Sudoku-solving: Sudoku-solving.md
    - Eight-queens-puzzle: Eight-queens-puzzle.md
    - Permutation-and-combination: Permutation-and-combination
    - Reading-list: Reading-list.md