nav:
    - Introduction: index.md
    - Merge-sort: Merge-sort
    - Quick-sort: Quick-sort
    - Quick-select: Quick-select
    - Timsort: Timsort
    - External-sorting: External-sorting    
    - LeetCode-Top-K: LeetCode-Top-K
    - Lexicographical-order-字典序: Lexicographical-order-字典序
