nav:
    - Introduction: index.md
    
    - Bubble-Sort: Bubble-Sort
    
    - Insertion-sort: Insertion-sort
    
    - Quick-sort: Quick-sort
    
    - Merge-sort: Merge-sort
    
    - Heapsort: Heapsort
    
    - Shellsort: Shellsort
    
    - Sort-linked-list: Sort-linked-list
    
    - Lexicographical-order-字典序: Lexicographical-order-字典序
    
    - LeetCode-912-排序数组: LeetCode-912-排序数组
    
    - Top-K-rank: Top-K-rank