nav:
    - Introduction: index.md
    - Merge-sort: Merge-sort
    - Quick-sort: Quick-sort
    - Timsort: Timsort

    - Lexicographical-order-字典序: Lexicographical-order-字典序
    - External-sorting: External-sorting