nav:
    - Introduction: index.md
    - Comparison-sort: Comparison-sort
    - Distribution-sort: Distribution-sort
    - Hybrid: Hybrid
    - Top-K-rank: Top-K-rank
    - LeetCode-912-排序数组: LeetCode-912-排序数组
    - LeetCode-581-最短无序连续子数组-中等: LeetCode-581-最短无序连续子数组-中等
    