nav:
    - Introduction: index.md
    - Segment-tree&interval-tree: Segment-tree&interval-tree
    - LeetCode-Merge-intervals: LeetCode-Merge-intervals
    - LeetCode-986-区间列表的交集: LeetCode-986-区间列表的交集
    - LeetCode-1854-人口最多的年份-简单: LeetCode-1854-人口最多的年份-简单
    - LeetCode-1893-检查是否区域内所有整数都被覆盖: LeetCode-1893-检查是否区域内所有整数都被覆盖
    - LeetCode-日程安排系列: LeetCode-日程安排系列
        