nav:
    - Introduction: index.md
    - LeetCode-438-找到字符串中所有字母异位词: LeetCode-438-找到字符串中所有字母异位词
    - LeetCode-567-字符串的排列: LeetCode-567-字符串的排列
    - LeetCode-1100-长度为K的无重复字符子串: LeetCode-1100-长度为K的无重复字符子串    
    - LeetCode-1839-所有元音按顺序排布的最长子字符串: LeetCode-1839-所有元音按顺序排布的最长子字符串
    