nav:
    - Recursive-data-type: Recursive-data-type
    - Recursion(computer-science): Recursion(computer-science)
    - Structural-and-generative-recursion: Structural-and-generative-recursion    
    - Term-with-recursion-in-computer-science: Term-with-recursion-in-computer-science.md
    - Corecursion: Corecursion.md