nav:
    - Introduction: index.md
    - Recursive-data-type: Recursive-data-type
    - Recursion(computer-science): Recursion(computer-science)
    - Structural-and-generative-recursion: Structural-and-generative-recursion    
    - Corecursion: Corecursion
