nav:
    - Summary: Summary
    - DFS-and-BFS: DFS-and-BFS.md
    - Iterative-deepening-depth-first-search: Iterative-deepening-depth-first-search.md
    - Best-first-search: Best-first-search.md
    - A-star-search-algorithm: A-star-search-algorithm.md
    - B-star-search-algorithm: B-star-search-algorithm.md
    - Beam-search: Beam-search.md
    
    
    