nav:
    - Introduction: index.md
    - Binary-search: Binary-search # 可以看做是search       
    - LeetCode-fast-slow-double-pointer-erase-remove-move-idiom: LeetCode-fast-slow-double-pointer-erase-remove-move-idiom
