nav:
    - Backtrack-enum-all-permutations-of-string: Backtrack-enum-all-permutations-of-string.md
    - Enum-distinct-permutation-of-with-duplicate: Enum-distinct-permutation-of-with-duplicate.md
    - Enum-permutation-reading-list: Enum-permutation-reading-list.md
    