nav:
    - Home: index.md
    - What-is-discrete-math: What-is-discrete-math
    - Discrete-math-and-computer-science: Discrete-math-and-computer-science.md
    - Structure: Structure
    - Guide: Guide
    - Book-Discrete-Mathematics-and-Its-Applications: Book-Discrete-Mathematics-and-Its-Applications