nav:
    - Home: index.md
    - Why-need-discrete-math: Why-need-discrete-math.md
    # 对一些专题进行总结，给出read guide
    - Guide: Guide
    - Book-Discrete-Mathematics-and-Its-Applications: Book-Discrete-Mathematics-and-Its-Applications