nav:
    - Home: index.md
    - Computer-science-is-discrete: Computer-science-is-discrete
    - Discrete-math: Discrete-math
    - Relation-structure-computation: Relation-structure-computation
    - Algorithm: Algorithm
    - Data-structure: Data-structure
    - Course-YSC2229-Introductory-Data-Structures-and-Algorithms: Course-YSC2229-Introductory-Data-Structures-and-Algorithms
    - LeetCode: LeetCode
    - Expert-labuladong: Expert-labuladong
    - Application: Application
    - TODO: TODO
    