nav:
    - Home: index.md
    
    - Computer-science-is-discrete: Computer-science-is-discrete
    
    - Discrete-math: Discrete-math
    
    - Relation-structure-computation: Relation-structure-computation
    
    - Algorithm: Algorithm
    
    - Data-structure: Data-structure
    
    - LeetCode: LeetCode
    
    - OI-Wiki: OI-Wiki
    
    - Expert-labuladong: Expert-labuladong
    
    - Expert-画解算法: Expert-画解算法
    
    - Expert-martinbroadhurst: Expert-martinbroadhurst
    
    - Expert-Emre-Bolat: Expert-Emre-Bolat
    
    - Expert-Edward-Elric: Expert-Edward-Elric
    
    - Expert-负雪明烛: Expert-负雪明烛
    
    - Expert-宫水三叶: Expert-宫水三叶
    
    - Expert-cheonhyangzhang: Expert-cheonhyangzhang
    
    - Course-YSC2229-Introductory-Data-Structures-and-Algorithms: Course-YSC2229-Introductory-Data-Structures-and-Algorithms
    
    - Course-cornell-cs3110: Course-cornell-cs3110
    
    - Book-Foundations-of-Computer-Science: Book-Foundations-of-Computer-Science

    - TODO: TODO
    