nav:
    - Home: index.md
    - Computer-science-is-discrete: Computer-science-is-discrete
    - Discrete-math: Discrete-math
    - Relation-structure-computation: Relation-structure-computation
    - Algorithm: Algorithm
    - Data-structure: Data-structure
    # 使用 Relation-structure-computation 章节中的思想来进行分析
    - Function-recursion-tree-stack: Function-recursion-tree-stack
    - Course-YSC2229-Introductory-Data-Structures-and-Algorithms: Course-YSC2229-Introductory-Data-Structures-and-Algorithms
    - LeetCode: LeetCode
    - Expert-labuladong: Expert-labuladong

    - TODO: TODO
    