nav:
    - Introduction: index.md
    - 数组: 数组
    - 动态规划: 动态规划
    - 树: 树
    - 滑动窗口: 滑动窗口
    - 并查集: 并查集
    - 链表: 链表
    - 双指针: 双指针
    - 贪心算法: 贪心算法
    - 数学: 数学
    - niukewang: niukewang
        
        