nav:
    - Introduction: index.md
    - Brute-force-search: Brute-force-search
    - DFS: DFS
    - DFS-backtracking: DFS-backtracking
    - BFS: BFS
    - BFS-branch-and-bound: BFS-branch-and-bound    
    