nav:
    - Introduction: index.md
    - Optimal-substructure: Optimal-substructure
    - Bellman-equation: Bellman-equation
    - Overlapping-subproblem: Overlapping-subproblem
    - DP: DP
    - Greedy: Greedy
