nav:
    - Introduction: index.md
    - Abstract-machine: Abstract-machine.md
    - Turinig-machine: Turinig-machine
    - Finite-state-machine: Finite-state-machine
    - Automata-software: Automata-software.md