nav:
    - Introduction: index.md    
    - Brute-force: Brute-force
    - Divide-and-Conquer: Divide-and-Conquer
    - Dynamic-Programming&Greedy-Algorithm: Dynamic-Programming&Greedy-Algorithm


    - Heuristic: Heuristic
    - Statistical-algorithms: Statistical-algorithms