nav:
    - Introduction: index.md
    - wikipedia-Algorithmic-paradigm: wikipedia-Algorithmic-paradigm    
    - Guide: Guide    
    - Brute-force: Brute-force
    - DP: DP
    - Greedy: Greedy    
    - Heuristic: Heuristic
    - Statistical-algorithms: Statistical-algorithms

    