nav:
    - Introduction: index.md
    - wikipedia-Algorithmic-paradigm: wikipedia-Algorithmic-paradigm    
    - 算法思维: 算法思维
    - Guide: Guide    
    - Brute-force: Brute-force
    - DP&Greedy: DP&Greedy
    - Heuristic: Heuristic
    - Statistical-algorithms: Statistical-algorithms

    