nav:
    - Introduction: index.md
    - wikipedia-Algorithmic-paradigm: wikipedia-Algorithmic-paradigm
    - DP: DP
    - Greedy: Greedy    
    - Heuristic: Heuristic
    - Statistical-algorithms: Statistical-algorithms

    